-- --------------------
-- 菜单管理
-- --------------------
DROP TABLE IF EXISTS SYS_MENU;
DROP TABLE IF EXISTS SYS_MENU_TYPE;

-- 菜单分类
CREATE TABLE SYS_MENU_TYPE (
	TYPE_ID VARCHAR(32) NOT NULL,
	TYPE_NAME VARCHAR(50) NOT NULL,
	TARGET VARCHAR(100),
	STATUS CHAR(1) NOT NULL DEFAULT '1',
	EDIT_TIME DATETIME
);

ALTER TABLE SYS_MENU_TYPE ADD CONSTRAINT SYS_MENU_TYPE_PK PRIMARY KEY (TYPE_ID);

-- 菜单
CREATE TABLE SYS_MENU (
	MENU_ID VARCHAR(32) NOT NULL,
	MENU_NAME VARCHAR(100) NOT NULL,
	TYPE_ID VARCHAR(32) NOT NULL,
	PARENT_ID VARCHAR(32),
	LINK_TYPE VARCHAR(20) NOT NULL,
	MENU_URL VARCHAR(200),
	DEFINE_TYPE VARCHAR(100),
	OPEN_TYPE VARCHAR(10),
	MENU_ICON1 VARCHAR(50),
	MENU_ICON2 VARCHAR(50),
	MENU_ICON3 VARCHAR(50),
	STATUS CHAR(1) NOT NULL DEFAULT '1',
	IS_LEAF CHAR(1) NOT NULL,
	SEQ INT(3) DEFAULT 0
);

ALTER TABLE SYS_MENU ADD CONSTRAINT SYS_MENU_PK PRIMARY KEY (MENU_ID);
ALTER TABLE SYS_MENU ADD CONSTRAINT SYS_MENU_FK1 FOREIGN KEY (TYPE_ID) REFERENCES SYS_MENU_TYPE (TYPE_ID);
ALTER TABLE SYS_MENU ADD CONSTRAINT SYS_MENU_FK2 FOREIGN KEY (PARENT_ID) REFERENCES SYS_MENU (MENU_ID);

-- --------------------
-- 用户管理
-- --------------------
DROP TABLE IF EXISTS SYS_USER_ONLINE;
DROP TABLE IF EXISTS SYS_USER_ROLE;
DROP TABLE IF EXISTS SYS_USER;

-- 用户
CREATE TABLE SYS_USER(
	USER_ID VARCHAR(100) NOT NULL,
	USER_TYPE VARCHAR(20) NOT NULL,
	USER_NAME VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	STATUS VARCHAR(2) NOT NULL DEFAULT '-1',
	ORGAN_ID VARCHAR(50),
	EDIT_TIME DATETIME,
	QUESTION VARCHAR(50),
	ANSWER VARCHAR(50),
	REGIST_TIME DATETIME
);

ALTER TABLE SYS_USER ADD CONSTRAINT SYS_USER_PK PRIMARY KEY (USER_ID);

-- --------------------
-- 权限管理
-- --------------------
DROP TABLE IF EXISTS SYS_ROLE_OPERATION;
DROP TABLE IF EXISTS SYS_ROLE;
DROP TABLE IF EXISTS SYS_OPERATION;
DROP TABLE IF EXISTS SYS_FUNCTION;
DROP TABLE IF EXISTS SYS_MODULE;

-- 模块
CREATE TABLE SYS_MODULE(
	MODULE_ID VARCHAR(32) NOT NULL,
	MODULE_NAME VARCHAR(50) NOT NULL,
	SEQ INT(3) DEFAULT 0
);

ALTER TABLE SYS_MODULE ADD CONSTRAINT SYS_MODULE_PK PRIMARY KEY (MODULE_ID);

-- 功能
CREATE TABLE SYS_FUNCTION(
	FUNCTION_ID VARCHAR(32) NOT NULL,
	FUNCTION_NAME VARCHAR(50) NOT NULL,
	MODULE_ID VARCHAR(32) NOT NULL,
	PARENT_ID VARCHAR(32),
	SEQ INT(3) DEFAULT 0
);

ALTER TABLE SYS_FUNCTION ADD CONSTRAINT SYS_FUNCTION_PK PRIMARY KEY (FUNCTION_ID);
ALTER TABLE SYS_FUNCTION ADD CONSTRAINT SYS_FUNCTION_FK1 FOREIGN KEY (MODULE_ID) REFERENCES SYS_MODULE (MODULE_ID);
ALTER TABLE SYS_FUNCTION ADD CONSTRAINT SYS_FUNCTION_FK2 FOREIGN KEY (PARENT_ID) REFERENCES SYS_FUNCTION (FUNCTION_ID);

-- 操作
CREATE TABLE SYS_OPERATION(
	OPERATION_ID VARCHAR(32) NOT NULL,
	OPERATION_NAME VARCHAR(50) NOT NULL,
	TARGET VARCHAR(200) NOT NULL,
	FUNCTION_ID VARCHAR(32) NOT NULL,
	SEQ INT(3) DEFAULT 0
);

ALTER TABLE SYS_OPERATION ADD CONSTRAINT SYS_OPERATION_PK PRIMARY KEY (OPERATION_ID);
ALTER TABLE SYS_OPERATION ADD CONSTRAINT SYS_OPERATION_FK1 FOREIGN KEY (FUNCTION_ID) REFERENCES SYS_FUNCTION (FUNCTION_ID);

-- 角色
CREATE TABLE SYS_ROLE(
	ROLE_ID VARCHAR(32) NOT NULL,
	ROLE_NAME VARCHAR(50) NOT NULL,
	ROLE_DESC VARCHAR(200)
);

ALTER TABLE SYS_ROLE ADD CONSTRAINT SYS_ROLE_PK PRIMARY KEY (ROLE_ID);

-- 角色操作
CREATE TABLE SYS_ROLE_OPERATION(
	ROLE_ID VARCHAR(32) NOT NULL,
	OPERATION_ID VARCHAR(32) NOT NULL
);

ALTER TABLE SYS_ROLE_OPERATION ADD CONSTRAINT SYS_ROLE_OPERATION_PK PRIMARY KEY (ROLE_ID, OPERATION_ID);
ALTER TABLE SYS_ROLE_OPERATION ADD CONSTRAINT SYS_ROLE_OPERATION_FK1 FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE (ROLE_ID);
ALTER TABLE SYS_ROLE_OPERATION ADD CONSTRAINT SYS_ROLE_OPERATION_FK2 FOREIGN KEY (OPERATION_ID) REFERENCES SYS_OPERATION (OPERATION_ID);

-- 用户角色
CREATE TABLE SYS_USER_ROLE(
	USER_ID VARCHAR(50) NOT NULL,
	ROLE_ID VARCHAR(32) NOT NULL
);

ALTER TABLE SYS_USER_ROLE ADD CONSTRAINT SYS_USER_ROLE_PK PRIMARY KEY (USER_ID, ROLE_ID);

-- 在线用户
CREATE TABLE SYS_USER_ONLINE(
	ID VARCHAR(32) NOT NULL,
	USER_ID VARCHAR(100) NOT NULL,
	LOGIN_IP VARCHAR(50),
	SESSION_ID VARCHAR(50),
	LOGIN_TIME DATETIME,
	LOGOUT_TIME DATETIME
);

ALTER TABLE SYS_USER_ONLINE ADD CONSTRAINT SYS_USER_ONLINE_PK PRIMARY KEY (ID);

-- --------------------
-- 门户管理
-- --------------------
DROP TABLE IF EXISTS SYS_DEFAULT_PAGE;
CREATE TABLE SYS_DEFAULT_PAGE (
	PAGE_ID VARCHAR(32) NOT NULL,
	PAGE_NAME VARCHAR(50) NOT NULL,
	TARGET_TYPE VARCHAR(20),
	TARGET_ID VARCHAR(50),
	PAGE_URL VARCHAR(200),
	NOTE VARCHAR(200),
	SEQ INT(3) DEFAULT 0
);

ALTER TABLE SYS_DEFAULT_PAGE ADD CONSTRAINT SYS_DEFAULT_PAGE_PK PRIMARY KEY (PAGE_ID);
