-- --------------------
-- 属性管理
-- --------------------
DROP TABLE IF EXISTS SYS_PROP;

-- 属性
CREATE TABLE SYS_PROP(
	PROP_ID VARCHAR(200) NOT NULL,
	PROP_VALUE VARCHAR(100) NOT NULL,
	PROP_DESC VARCHAR(100),
	EDIT_TIME DATETIME,
	SEQ INT(6) DEFAULT 0
);

ALTER TABLE SYS_PROP ADD CONSTRAINT SYS_PROP_PK PRIMARY KEY (PROP_ID);

-- --------------------
-- 字典管理
-- --------------------
DROP TABLE IF EXISTS SYS_DICT_ITEM;
DROP TABLE IF EXISTS SYS_DICT;

-- 字典
CREATE TABLE SYS_DICT(
	DICT_CODE VARCHAR(100) NOT NULL,
	DICT_NAME VARCHAR(200) NOT NULL,
	EDIT_TIME DATETIME,
	DICT_DESC VARCHAR(100)
);

ALTER TABLE SYS_DICT ADD CONSTRAINT SYS_DICT_PK PRIMARY KEY (DICT_CODE);

-- 字典项
CREATE TABLE SYS_DICT_ITEM(
	ITEM_CODE VARCHAR(100) NOT NULL,
	ITEM_VALUE VARCHAR(200) NOT NULL,
	DICT_CODE VARCHAR(100) NOT NULL,
	PARENT_CODE VARCHAR(100),
	EDIT_TIME DATETIME,
	ITEM_DESC VARCHAR(100),
	SEQ INT(6) DEFAULT 0,
	STATUS CHAR(1) NOT NULL DEFAULT '1'
);

ALTER TABLE SYS_DICT_ITEM ADD CONSTRAINT SYS_DICT_ITEM_PK PRIMARY KEY (DICT_CODE, ITEM_CODE);
ALTER TABLE SYS_DICT_ITEM ADD CONSTRAINT SYS_DICT_ITEM_FK1 FOREIGN KEY (DICT_CODE) REFERENCES SYS_DICT (DICT_CODE);

-- --------------------
-- 流水号管理
-- --------------------
DROP TABLE IF EXISTS SYS_SERIAL_NO;

-- 流水号
CREATE TABLE SYS_SERIAL_NO(
	NO_CODE VARCHAR(100) NOT NULL,
	NO_NAME VARCHAR(200) NOT NULL,
	NO_PREFIX VARCHAR(100),
	NO_SUFFIX VARCHAR(100),
	NO_VALUE INT(13) NOT NULL,
	NO_LENGTH INT(2) NOT NULL,
	NO_TYPE VARCHAR(10),
	EDIT_TIME DATETIME
);

ALTER TABLE SYS_SERIAL_NO ADD CONSTRAINT SYS_SERIAL_NO_PK PRIMARY KEY (NO_CODE);

-- --------------------
-- 组织机构管理
-- --------------------
DROP TABLE IF EXISTS SYS_ORGAN;
DROP TABLE IF EXISTS SYS_ORGAN_RULE;
DROP TABLE IF EXISTS SYS_ORGAN_TYPE;

-- 组织机构类型
CREATE TABLE SYS_ORGAN_TYPE(
	TYPE_ID VARCHAR(50) NOT NULL,
	TYPE_NAME VARCHAR(100) NOT NULL,
	IS_LEAF CHAR(1) NOT NULL,
	SEQ INT(3) DEFAULT 0
);

ALTER TABLE SYS_ORGAN_TYPE ADD CONSTRAINT SYS_ORGAN_TYPE_PK PRIMARY KEY (TYPE_ID);

-- 组织机构规则
CREATE TABLE SYS_ORGAN_RULE(
	TYPE_ID VARCHAR(50) NOT NULL,
	CHILD_ID VARCHAR(50) NOT NULL
);

ALTER TABLE SYS_ORGAN_RULE ADD CONSTRAINT SYS_ORGAN_RULE_PK PRIMARY KEY (TYPE_ID, CHILD_ID);
ALTER TABLE SYS_ORGAN_RULE ADD CONSTRAINT SYS_ORGAN_RULE_FK1 FOREIGN KEY (TYPE_ID) REFERENCES SYS_ORGAN_TYPE (TYPE_ID);
ALTER TABLE SYS_ORGAN_RULE ADD CONSTRAINT SYS_ORGAN_RULE_FK2 FOREIGN KEY (CHILD_ID) REFERENCES SYS_ORGAN_TYPE (TYPE_ID);

-- 组织机构
CREATE TABLE SYS_ORGAN(
	ORGAN_ID VARCHAR(50) NOT NULL,
	ORGAN_NAME VARCHAR(100) NOT NULL,
	TYPE_ID VARCHAR(50) NOT NULL,
	FULL_NAME VARCHAR(200) NOT NULL,
	PARENT_ID VARCHAR(50),
	SEQ INT(6) DEFAULT 0,
	STATUS CHAR(1) NOT NULL DEFAULT '1'
);

ALTER TABLE SYS_ORGAN ADD CONSTRAINT SYS_ORGAN_PK PRIMARY KEY (ORGAN_ID);
ALTER TABLE SYS_ORGAN ADD CONSTRAINT SYS_ORGAN_FK1 FOREIGN KEY (TYPE_ID) REFERENCES SYS_ORGAN_TYPE (TYPE_ID);
ALTER TABLE SYS_ORGAN ADD CONSTRAINT SYS_ORGAN_FK2 FOREIGN KEY (PARENT_ID) REFERENCES SYS_ORGAN (ORGAN_ID);

-- --------------------
-- 行政区划管理
-- --------------------
DROP TABLE IF EXISTS SYS_CANT;
DROP TABLE IF EXISTS SYS_CANT_TYPE;

-- 行政区划类型
CREATE TABLE SYS_CANT_TYPE(
	TYPE_ID VARCHAR(20) NOT NULL,
	TYPE_NAME VARCHAR(50) NOT NULL,
	SEQ INT(3) DEFAULT 0
);

ALTER TABLE SYS_CANT_TYPE ADD CONSTRAINT SYS_CANT_TYPE_PK PRIMARY KEY (TYPE_ID);

-- 行政区划
CREATE TABLE SYS_CANT(
	CANT_CODE VARCHAR(32) NOT NULL,
	CANT_NAME VARCHAR(32) NOT NULL,
	FULL_NAME VARCHAR(32) NOT NULL,
	TYPE_ID VARCHAR(32) NOT NULL,
	PARENT_CODE VARCHAR(32),
	POSTCODE CHAR(6),
	PHONECODE VARCHAR(4),
	STATUS CHAR(1) NOT NULL DEFAULT '1',
	SEQ INT(3) DEFAULT 0
);

ALTER TABLE SYS_CANT ADD CONSTRAINT SYS_CANT_PK PRIMARY KEY (CANT_CODE);
ALTER TABLE SYS_CANT ADD CONSTRAINT SYS_CANT_FK1 FOREIGN KEY (TYPE_ID) REFERENCES SYS_CANT_TYPE (TYPE_ID);
ALTER TABLE SYS_CANT ADD CONSTRAINT SYS_CANT_FK2 FOREIGN KEY (PARENT_CODE) REFERENCES SYS_CANT (CANT_CODE);

-- --------------------
-- 通讯录
-- --------------------
DROP TABLE IF EXISTS SYS_LINK;

CREATE TABLE SYS_LINK(
	ID VARCHAR(50) NOT NULL,
	TARGET VARCHAR(50),
	NAME VARCHAR(50) NOT NULL,
	CORP_NAME VARCHAR(100),
	POSTCODE VARCHAR(10),
	ADDR_PROVINCE_ID VARCHAR(10),
	ADDR_PROVINCE_NAME VARCHAR(50),
	ADDR_CITY_ID VARCHAR(10),
	ADDR_CITY_NAME VARCHAR(50),
	ADDR_COUNTY_ID VARCHAR(10),
	ADDR_COUNTY_NAME VARCHAR(50),
	ADDR_DETAIL VARCHAR(100),
	ADDRESS VARCHAR(200),
	PHONE VARCHAR(20),
	FAX VARCHAR(20),
	MOBILE VARCHAR(20),
	EMAIL VARCHAR(50),
	QQ VARCHAR(20),
	CREATE_TIME DATETIME NOT NULL,
	EDIT_TIME DATETIME NOT NULL
);

ALTER TABLE SYS_LINK ADD CONSTRAINT SYS_LINK_PK PRIMARY KEY (ID);