
-- DEMO表1
DROP TABLE IF EXISTS DEMO_TABLE1;
CREATE TABLE DEMO_TABLE1(
	ID INT(13) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) UNIQUE,
	AGE INT(3),
	NOTE VARCHAR(200),
	PRIMARY KEY(ID)
);

INSERT INTO DEMO_TABLE1(ID, NAME, AGE)
VALUES('1001', '测试一', 18);

INSERT INTO DEMO_TABLE1(ID, NAME, AGE)
VALUES('1002', '测试二', 20);

INSERT INTO DEMO_TABLE1(ID, NAME, AGE)
VALUES('1003', '测试三', 22);

INSERT INTO DEMO_TABLE1(ID, NAME, AGE)
VALUES('1004', '测试四', 18);

INSERT INTO DEMO_TABLE1(ID, NAME, AGE)
VALUES('1005', '测试五', 20);

INSERT INTO DEMO_TABLE1(ID, NAME, AGE)
VALUES('1006', '测试六', 22);

INSERT INTO DEMO_TABLE1(ID, NAME, AGE)
VALUES('1007', '测试七', 18);

INSERT INTO DEMO_TABLE1(ID, NAME, AGE)
VALUES('1008', '测试八', 20);

INSERT INTO DEMO_TABLE1(ID, NAME, AGE)
VALUES('1009', '测试九', 22);

INSERT INTO DEMO_TABLE1(ID, NAME, AGE)
VALUES('1010', '测试10', 18);

INSERT INTO DEMO_TABLE1(ID, NAME, AGE)
VALUES('1011', '测试11', 20);

INSERT INTO DEMO_TABLE1(ID, NAME, AGE)
VALUES('1012', '测试12', 22);

-- DEMO表2
DROP TABLE IF EXISTS DEMO_TABLE2;
CREATE TABLE DEMO_TABLE2(
	ID INT(13) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) UNIQUE,
	NOTE VARCHAR(200),
	PRIMARY KEY(ID)
);

INSERT INTO DEMO_TABLE2(ID, NAME)
VALUES(1001, '测试一');

INSERT INTO DEMO_TABLE2(ID, NAME)
VALUES(1002, '测试二');

INSERT INTO DEMO_TABLE2(ID, NAME)
VALUES(1003, '测试三');