-- 流水号
INSERT INTO SYS_SERIAL_NO(NO_CODE, NO_NAME, NO_PREFIX, NO_SUFFIX, NO_VALUE, NO_LENGTH, NO_TYPE, EDIT_TIME)
VALUES('SYS_ORGAN_ID', '组织机构主键', NULL, NULL, 10000000, 8, NULL, NOW());

INSERT INTO SYS_SERIAL_NO(NO_CODE, NO_NAME, NO_PREFIX, NO_SUFFIX, NO_VALUE, NO_LENGTH, NO_TYPE, EDIT_TIME)
VALUES('SYS_LINK_ID', '通讯录主键', NULL, NULL, 10000000, 8, NULL, NOW());

-- 组织机构类型
INSERT INTO SYS_ORGAN_TYPE(TYPE_ID, TYPE_NAME, IS_LEAF, SEQ)
VALUES('CORP', '单位', '0', 1);

INSERT INTO SYS_ORGAN_TYPE(TYPE_ID, TYPE_NAME, IS_LEAF, SEQ)
VALUES('DEPT', '部门', '0', 2);

INSERT INTO SYS_ORGAN_TYPE(TYPE_ID, TYPE_NAME, IS_LEAF, SEQ)
VALUES('POST', '岗位', '0', 3);

INSERT INTO SYS_ORGAN_TYPE(TYPE_ID, TYPE_NAME, IS_LEAF, SEQ)
VALUES('EMP', '员工', '1', 4);

-- 组织机构规则
INSERT INTO SYS_ORGAN_RULE(TYPE_ID, CHILD_ID)
VALUES('CORP', 'CORP');

INSERT INTO SYS_ORGAN_RULE(TYPE_ID, CHILD_ID)
VALUES('CORP', 'DEPT');

INSERT INTO SYS_ORGAN_RULE(TYPE_ID, CHILD_ID)
VALUES('CORP', 'POST');

INSERT INTO SYS_ORGAN_RULE(TYPE_ID, CHILD_ID)
VALUES('DEPT', 'DEPT');

INSERT INTO SYS_ORGAN_RULE(TYPE_ID, CHILD_ID)
VALUES('DEPT', 'POST');

INSERT INTO SYS_ORGAN_RULE(TYPE_ID, CHILD_ID)
VALUES('POST', 'EMP');

-- 行政区划类型
INSERT INTO SYS_CANT_TYPE(TYPE_ID, TYPE_NAME, SEQ)
VALUES('0', '国家', 0);

INSERT INTO SYS_CANT_TYPE(TYPE_ID, TYPE_NAME, SEQ)
VALUES('1', '省（自治区、直辖市）', 1);

INSERT INTO SYS_CANT_TYPE(TYPE_ID, TYPE_NAME, SEQ)
VALUES('2', '地（市）', 2);

INSERT INTO SYS_CANT_TYPE(TYPE_ID, TYPE_NAME, SEQ)
VALUES('3', '区（县）', 3);

INSERT INTO SYS_CANT_TYPE(TYPE_ID, TYPE_NAME, SEQ)
VALUES('4', '街道（乡、镇）', 4);

-- 行政区划