-- 流水号
INSERT INTO SYS_SERIAL_NO(NO_CODE, NO_NAME, NO_PREFIX, NO_SUFFIX, NO_VALUE, NO_LENGTH, NO_TYPE, EDIT_TIME)
VALUES('SYS_MENU_ID', '菜单主键', 'M', NULL, 1000000, 8, NULL, NOW());

INSERT INTO SYS_SERIAL_NO(NO_CODE, NO_NAME, NO_PREFIX, NO_SUFFIX, NO_VALUE, NO_LENGTH, NO_TYPE, EDIT_TIME)
VALUES('SYS_MODULE_ID', '模块主键', 'MD', NULL, 10000000, 8, NULL, NOW());

INSERT INTO SYS_SERIAL_NO(NO_CODE, NO_NAME, NO_PREFIX, NO_SUFFIX, NO_VALUE, NO_LENGTH, NO_TYPE, EDIT_TIME)
VALUES('SYS_FUNCTION_ID', '功能主键', 'FC', NULL, 10000000, 8, NULL, NOW());

INSERT INTO SYS_SERIAL_NO(NO_CODE, NO_NAME, NO_PREFIX, NO_SUFFIX, NO_VALUE, NO_LENGTH, NO_TYPE, EDIT_TIME)
VALUES('SYS_OPERATION_ID', '操作主键', 'OP', NULL, 10000000, 8, NULL, NOW());

INSERT INTO SYS_SERIAL_NO(NO_CODE, NO_NAME, NO_PREFIX, NO_SUFFIX, NO_VALUE, NO_LENGTH, NO_TYPE, EDIT_TIME)
VALUES('SYS_DEFAULT_PAGE_ID', '首页主键', 'P', NULL, 10000000, 8, NULL, NOW());

-- 菜单类型
INSERT INTO SYS_MENU_TYPE (TYPE_ID, TYPE_NAME, TARGET, STATUS, EDIT_TIME)
VALUES('SYSTEM', '预置菜单', NULL, '1', NOW());

INSERT INTO SYS_MENU_TYPE (TYPE_ID, TYPE_NAME, TARGET, STATUS, EDIT_TIME)
VALUES('DEFAULT', '默认菜单', NULL, '1', NOW());

INSERT INTO SYS_MENU_TYPE (TYPE_ID, TYPE_NAME, TARGET, STATUS, EDIT_TIME)
VALUES('USER', '用户菜单', NULL, '1', NOW());

-- 用户
INSERT INTO SYS_USER (USER_ID, USER_TYPE, USER_NAME, PASSWORD, STATUS, EDIT_TIME, QUESTION, ANSWER, REGIST_TIME)
VALUES('SUPERADMIN', 'ADMIN', '超级管理员', '1', '1', NOW(), NULL, NULL, NOW());

INSERT INTO SYS_USER (USER_ID, USER_TYPE, USER_NAME, PASSWORD, STATUS, EDIT_TIME, QUESTION, ANSWER, REGIST_TIME)
VALUES('ADMIN', 'ADMIN', '管理员', '1', '1', NOW(), NULL, NULL, NOW());

-- 角色
INSERT INTO SYS_ROLE(ROLE_ID, ROLE_NAME) 
VALUES('SUPERADMIN', '超级管理员');

INSERT INTO SYS_ROLE(ROLE_ID, ROLE_NAME) 
VALUES('ADMIN', '系统管理员');

-- 用户角色
INSERT INTO SYS_USER_ROLE(USER_ID, ROLE_ID)
VALUES('SUPERADMIN', 'SUPERADMIN');

INSERT INTO SYS_USER_ROLE(USER_ID, ROLE_ID)
VALUES('ADMIN', 'ADMIN');

-- 默认页面
INSERT INTO SYS_DEFAULT_PAGE (PAGE_ID, PAGE_NAME, TARGET_TYPE, TARGET_ID, PAGE_URL, SEQ)
VALUES('P10000000', '首页', 'ROLE', 'SUPERADMIN', 'jsp/xianfeng/admin/welcome.jsp', 0);